[project]
name = "ros2-federated"
version = "0.1.0"
description = "Python project for Federated RL trainning loop"
authors = [
    {name = "Gerardo Gutierrez"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [
    { include = "ros2_federated", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
