client_1:
  ros__parameters:
    dataset: "mnist"

client_2:
  ros__parameters:
    dataset: "mnist"

client_3:
  ros__parameters:
    dataset: "mnist"

client_4:
  ros__parameters:
    dataset: "mnist"