agent_1:
  ros__parameters:
    agent_name: "agent_1"
    random_coords: true
    checkpoint: "checkpoints_latest/agent_1/2026-04-07T21-10-48/ros_net_20000.chkpt"

agent_2:
  ros__parameters:
    agent_name: "agent_2"
    random_coords: true
    checkpoint: "checkpoints_latest/agent_2/2026-04-07T21-10-48/ros_net_20000.chkpt"

agent_3:
  ros__parameters:
    agent_name: "agent_3"
    random_coords: true
    checkpoint: "checkpoints_latest/agent_3/2026-04-07T21-10-48/ros_net_20000.chkpt"

agent_4:
  ros__parameters:
    agent_name: "agent_4"
    random_coords: true
    checkpoint: "checkpoints_latest/agent_4/2026-04-07T21-10-48/ros_net_20000.chkpt"

# agent_5:
#   ros__parameters:
#     agent_name: "agent_5"
#     checkpoint: "checkpoints_train/agent_5/2026-02-12T20-31-35/ros_net_1.chkpt"

# agent_6:
#   ros__parameters:
#     agent_name: "agent_6"
#     checkpoint: "checkpoints_train/agent_6/2026-02-12T20-31-35/ros_net_1.chkpt"

# agent_7:
#   ros__parameters:
#     agent_name: "agent_7"
#     checkpoint: "checkpoints_train/agent_7/2026-02-12T20-31-35/ros_net_1.chkpt"

# agent_8:
#   ros__parameters:
#     agent_name: "agent_8"
#     checkpoint: "checkpoints_train/agent_8/2026-02-12T20-31-35/ros_net_1.chkpt"